apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: "cp4i-demo"
  name: cp4i-ace-demo
spec:
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
  selector:
    matchLabels:
      app: "cp4i-demo"
status: {}
