apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: send-to-webhook-slack
spec:
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this workspace  
  params:
  - name: webhook-secret
    type: string
    description: secret name of the slack app webhook URL (key is url)
    default: slack-webhook-secret
  - name: imageTag
    type: string
  - name: imageUrl
    type: string
  - name: message
    type: string
    description: plain text message
  steps:
  - name: post
    image: curlimages/curl:7.68.0
    script: |
      #!/bin/sh
      /usr/bin/curl -X POST -H 'Content-type: application/json' --data '{"text":"$(params.message)"}' $URL
    env:
    - name: URL
      valueFrom:
        secretKeyRef:
          name: $(params.webhook-secret)
          key: url
