kind: Secret
apiVersion: v1
metadata:
  name: artifactory-credentials
data:
  ARTIFACTORY_PASSWORD: <Base64 encoded value of admin password>
  ARTIFACTORY_URL: <Base64 encoded value of Artifactory URL>
  # ARTIFACTORY_USER set to Base64 encoded value of "admin"
  ARTIFACTORY_USER: YWRtaW4=
type: Opaque
