kind: Secret
apiVersion: v1
metadata:
  name: github-access-token
  annotations:
    tekton.dev/git-0: 'https://github.com'
data:
  password: <Base64 encoded github token>
  username: <Base64 encoded github username>
type: kubernetes.io/basic-auth
