kind: Secret
apiVersion: v1
metadata:
  name: ibm-cr-push-secret
  annotations:
    tekton.dev/docker-0: us.icr.io
data:
  password: <Base64 encoded IBM Cloud API key>
  username: <Base64 encoded github token>
type: kubernetes.io/basic-auth
