apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: sample-ace-trigger-template
spec:
  params:
    - name: gitUrl
      description: The git repository URL for the msad-integration build and deploy
      default: https://github.com/cs-tsui/devops-demo-sample-ace-project
    - name: gitRevision
      description: The git revision to build
      default: master
    - name: gitRepo
      description: Name of the git repository
      default: devops-demo-sample-ace-project
    - name: serviceAccountName
      description: The service account name to use to run the pipeline
      default: my-pipeline-sa
    - name: imageContext
      description: The image context root in the image registry where the image is stored
      default: dev-cst
    - name: imageTag
      description: The image tag
      default: latest
  resourcetemplates:

    - kind: Secret
      apiVersion: v1
      metadata:
        name: github-access-token
        annotations:
          tekton.dev/git-0: 'https://github.com'
      stringData:
        password: $(params.github_token)
        username: github-username
      type: kubernetes.io/basic-auth

    - kind: Secret
      apiVersion: v1
      metadata:
        name: artifactory-credentials
      data:
        ARTIFACTORY_PASSWORD: $(params.artifactory_password)
        ARTIFACTORY_URL: >-
          aHR0cHM6Ly9hcnRpZmFjdG9yeS10b29scy5jc3Qtcm9rcy1zbS02Y2NkN2YzNzhhZTgxOTU1M2QzN2Q1ZjJlZTE0MmJkNi0wMDAwLnNqYzA0LmNvbnRhaW5lcnMuYXBwZG9tYWluLmNsb3Vk
        ARTIFACTORY_USER: YWNlLXVzZXI=
      type: Opaque

    # Docker Pull/Push Secret
    - apiVersion: v1
      kind: Secret
      metadata:
        name: private-registry-secret
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: $(params.dockerconfigjson)

    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: my-pipeline-sa
      secrets:
      - name: private-registry-secret
      imagePullSecrets:
      - name: private-registry-secret

    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: ace-pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce

    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        serviceAccountNames:
          - taskName: build-task
            serviceAccountName: $(params.serviceAccountName)
        # serviceAccountName: $(params.serviceAccountName)
        pipelineRef:
          name: simple-pipeline
        params:
          - name: gitUrl
            value: $(params.gitUrl)
          - name: gitRevision
            value: $(params.gitRevision)
          - name: imageUrl
            value: "us.icr.io/$(params.imageContext)/$(params.project)"
            # value: 169.62.82.19:32265/my-docker-reg/sample-toolchain-ace
          - name: imageTag
            value: $(params.imageTag)
          - name: gitRepo
            value: $(params.gitRepo)
          - name: pathToYamlFile
            value: "k8s"
          - name: pathToContext
            value: "workspace"
          - name: extraArgs
            value: --skip-tls-verify
          - name: project
            value: $(params.project)
          # Defined in IBM Cloud Environment Properties
          - name: service_account_token
            value: $(params.service_account_token)
          - name: cluster_url
            value: $(params.cluster_url)

        timeout: "1h0m0s"
        workspaces:
          - name: git-source
            persistentVolumeClaim:
              claimName: ace-pipelinerun-$(uid)-pvc
