# Trigger binding for commits
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: sample-ace-triggerbinding
spec:
  params:
  - name: gitUrl
    value: $(event.repository.clone_url)
  - name: gitRevision
    value: $(event.head_commit.id)
  - name: imageContext
    value: custom-ace-images
  - name: gitRepo
    value: $(event.repository.name)
  - name: serviceAccountName
    value: my-pipeline-sa
  - name: imageTag
    value: $(event.head_commit.id)
---
# Trigger binding for PRs
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: sample-ace-triggerbinding-pr
spec:
  params:
  - name: gitUrl
    value: $(event.repository.clone_url)
  - name: gitRevision
    value: $(event.pull_request.head.sha)
  - name: imageContext
    value: custom-ace-images
  - name: gitRepo
    value: $(event.repository.name)
  - name: serviceAccountName
    value: my-pipeline-sa
  - name: imageTag
    value: $(event.pull_request.head.sha)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: sample-ace-triggerbinding-manual
spec:
  params:
  - name: gitUrl
    value: https://github.com/cs-tsui/devops-demo-sample-ace-project
  - name: gitRevision
    value: ''
  - name: imageContext
    value: custom-ace-images
  - name: gitRepo
    value: devops-demo-sample-ace-project
  - name: serviceAccountName
    value: my-pipeline-sa
  - name: imageTag
    # value: $(event.pull_request.head.sha)
    value: latest
  # - name: project
  #   value: sampleaceproject